spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/mentalapp}
    username: ${DATABASE_USERNAME:mental}
    password: ${DATABASE_PASSWORD:mentalpw}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080

logging:
  level:
    com.mentalapp: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-here-make-it-long-and-secure}
  access-token:
    expiration: 900000 # 15 minutes in milliseconds
  refresh-token:
    expiration: 604800000 # 7 days in milliseconds
  issuer: mental-health-app

gemini:
  api:
    key: ${GEMINI_API_KEY:}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent
